import Link from "next/link";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Terms of Service — RenderDrop",
};

const SUPPORT_EMAIL = "vimalrajelash@gmail.com";

export default function TermsPage() {
  return (
    <div className="flex flex-1 flex-col">
      <header className="flex items-center justify-between border-b border-blueprint-light px-6 py-4">
        <Link href="/">
          <p className="font-tech text-xs tracking-widest text-cyan-accent">
            RENDERDROP
          </p>
          <p className="font-body text-xs text-graphite">Terms of Service</p>
        </Link>
      </header>

      <main className="mx-auto w-full max-w-2xl flex-1 px-6 py-10">
        <h1 className="font-display text-2xl font-semibold text-linework">
          Terms of Service
        </h1>
        <p className="mt-2 font-tech text-xs text-graphite">
          Last updated August 17, 2026
        </p>

        <p className="mt-6 border border-blueprint-lighter bg-blueprint-light/40 px-4 py-3 font-body text-sm text-graphite">
          This is a plain-language starting template, not a substitute for
          legal advice. Have it reviewed before relying on it for compliance.
        </p>

        <div className="mt-8 space-y-8 font-body text-sm leading-relaxed text-linework/90">
          <Section title="The service">
            <p>
              RenderDrop turns an uploaded SketchUp viewport export into an
              AI-generated photorealistic render. By creating an account or
              using the service, you agree to these terms.
            </p>
          </Section>

          <Section title="Your account">
            <p>
              Keep your login credentials to yourself. You&rsquo;re
              responsible for activity on your account. One account per
              person — creating multiple accounts to work around usage
              limits is not allowed and may result in suspension.
            </p>
          </Section>

          <Section title="Usage limits">
            <p>
              Renders and analyses are capped per day. Limits exist because
              each one has a real cost to us, may change without notice, and
              are not a guarantee of availability.
            </p>
          </Section>

          <Section title="AI-generated output">
            <p>
              Renders are generated by a third-party AI model and may
              contain inaccuracies, artifacts, or details that don&rsquo;t
              match the uploaded model exactly. Output is provided for
              visualization purposes only — review it yourself before using
              it for construction, client delivery, or any decision where
              accuracy matters. We make no warranty as to its accuracy or
              fitness for a particular purpose.
            </p>
          </Section>

          <Section title="Your content">
            <p>
              You keep ownership of what you upload and of the renders
              generated from it. You grant us the license needed to process
              your uploads (including sending them to our AI provider) in
              order to provide the service. Don&rsquo;t upload anything you
              don&rsquo;t have the rights to, or anything illegal.
            </p>
          </Section>

          <Section title="Acceptable use">
            <ul className="list-disc space-y-1 pl-5">
              <li>No attempting to bypass usage limits or security controls.</li>
              <li>No uploading illegal, infringing, or abusive content.</li>
              <li>
                No automated bulk use of the service outside the documented
                API surface.
              </li>
            </ul>
          </Section>

          <Section title="Availability">
            <p>
              The service is provided &ldquo;as is,&rdquo; without an
              uptime guarantee. We may change, suspend, or discontinue any
              part of it at any time.
            </p>
          </Section>

          <Section title="Termination">
            <p>
              We may suspend or terminate accounts that violate these terms,
              particularly around usage-limit abuse. You can stop using the
              service, or request account deletion, at any time — see the{" "}
              <Link
                href="/privacy"
                className="text-cyan-accent underline underline-offset-4"
              >
                Privacy Policy
              </Link>{" "}
              for how.
            </p>
          </Section>

          <Section title="Liability">
            <p>
              To the extent permitted by law, we&rsquo;re not liable for
              damages arising from your use of the service or reliance on
              AI-generated output, including decisions made based on a
              render&rsquo;s accuracy.
            </p>
          </Section>

          <Section title="Changes to these terms">
            <p>
              If these terms change materially, we&rsquo;ll update the date
              at the top of this page.
            </p>
          </Section>

          <Section title="Contact">
            <p>
              Questions about these terms:{" "}
              <a
                href={`mailto:${SUPPORT_EMAIL}`}
                className="text-cyan-accent underline underline-offset-4"
              >
                {SUPPORT_EMAIL}
              </a>
              .
            </p>
          </Section>
        </div>
      </main>
    </div>
  );
}

function Section({
  title,
  children,
}: {
  title: string;
  children: React.ReactNode;
}) {
  return (
    <section>
      <h2 className="font-tech text-xs uppercase tracking-widest text-graphite">
        {title}
      </h2>
      <div className="mt-2">{children}</div>
    </section>
  );
}
